### ISSUE TITLE
请问Tree Encoder部分的代码是不是删除了 

### ISSUE THREAD

**Issue by fangchuanml** [zyxnlp/ACLT#1]
请问Tree Encoder部分的代码是不是删除了 
我没找到.. 能否麻烦告知一下在哪个文件里

**Comment by zyxnlp** [comment]
> 请问Tree Encoder部分的代码是不是删除了 我没找到.. 能否麻烦告知一下在哪个文件里

Hi, thanks for your attention! The code of Tree Encoder is in the script of attention.py. In fact, we try various calculations in Eq(9) on the original paper. For example, concatenate, sum, average, etc., turns out it has little effect on the results. You can try whatever tree encoder you want.

**Comment by fangchuanml** [comment]
谢谢 懂了！ 另外请问能不能提供一下复现的 KumaGCN+BERT的代码呢 万分感谢！邮箱fangchuanml@163.com
